version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle-gastos
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
